### ISSUE TITLE
L'impression tronque des parties

### ISSUE THREAD

**Issue by rdugau** [GoOz/wfrp-sheet#10]
L'impression n'est pas possible.
Avec une mise à l'échelle standard, les frames sont tronquées.

![image](https://user-images.githubusercontent.com/56961532/218709730-71f4a533-0242-44a4-ac6d-eda100ea121a.png)

**Comment by GoOz** [comment]
En effet, j'ai pas prévu de style pour l'impression mais je peux rajouter ça à terme. 👍

**Comment by GoOz** [comment]
Bon va falloir me convaincre, pourquoi imprimer l'app alors qu'il y a un fichier PDF officiel prompt à l'impression ?
Ce serait quoi la valeur ajoutée ?

Parce que là, compte tenu de plein de paramètres différents, l'impression, si je la fais, ressemblerait plus à la version mobile de l'app (les blocs les uns en dessous des autres) mais en plus large qu'à la version portrait de l'app.

**Comment by rdugau** [comment]
> pourquoi imprimer l'app


Ah bin tout simplement parcequ'on aime bien avoir sa feuille en version papier.
Et si on utilise l'app on n'utilise plus le pdf ;-)

**Comment by rdugau** [comment]
Il suffit d'imprimer l'écran tel qu'il apparait
Par contre il faut simuler un viewport de la bonne taille.

Mon idée :
On prend une feuille A4, le type a des marges par défaut de 10 mm. On a donc 20x28,7 cm
Pour utiliser un truc standard on dit 96 dpi => viewport = 28,7/2,54*96  x  20/2,54*96 = 1085 x 756

J'obtiens ça :
![image](https://user-images.githubusercontent.com/56961532/219311104-64f64404-daea-4cd3-87ee-ab30777134f6.png)
![image](https://user-images.githubusercontent.com/56961532/219311337-226a97ec-5c84-43fb-a733-c6924a8267c0.png)

**Comment by GoOz** [comment]
Oui mais non ça marchera pas comme ça, parce que les zones avec champ texte libre peuvent bien plus grand et nécessiter un scroll, scroll qu'on pourra pas avoir sur papier (aux dernières nouvelles 😛), ce qui veut dire que je peux pas garder ce layout et je serais obligé de faire en sorte que chaque bloc soit aussi grand que son contenu donc le plus simple serait de mettre les blocs les uns en dessous des autres, ce qui fonctionnera mais sera pas top visuellement, surtout comparé au PDF.

**Comment by GoOz** [comment]
Je vais pas le faire parce que c'est chiant à tester et j'en vois pas l'intérêt. À réouvrir si on me donne un véritable bonus. :)

**Comment by rdugau** [comment]
> et j'en vois pas l'intérêt

What ?
C'est un must have..

Comme mentionné au début
> Ah bin tout simplement parcequ'on aime bien avoir sa feuille en version papier.

Avis perso :
Si je ne peux pas imprimer, je préfère rester sur le pdf. Même si il ne fait pas les calculs.
Mais c'est perso. Je te laisse voir avec d'autres utilisateurs ...

**Comment by GoOz** [comment]
Je comprends pas. L'intérêt de l'app c'est de ne pas avoir de papier et d'avoir des fonctionnalités que ne propose pas le papier. Imprimer cette feuille c'est perdre toutes les fonctionnalités.
À la grande limite je pourrais concevoir que ça serve à imprimer temporairement parce que je sais pas ton ordi est pété ou que sais-je mais c'est tout.

**Comment by rdugau** [comment]
Et comment je donne ma feuille à mon MJ pour qu'il valide ?

Nan. Mais je sais pas qui a raison
A voir ce que les autres pensent ...

Perso je n'aime pas le démat sur ces trucs là (le JDR en général)

**Comment by GoOz** [comment]
> Et comment je donne ma feuille à mon MJ pour qu'il valide ?
> 
> Nan. Mais je sais pas qui a raison A voir ce que les autres pensent ...
> 
Moi évidemment :)
> Perso je n'aime pas le démat sur ces trucs là (le JDR en général)
Bah donc t'es pas la cible de l'app en fait. C'est spécifiquement fait pour les gens qui ne veulent pas du papier (comme moi)
