### ISSUE TITLE
La somme des blessures ne se mets pas à jour lorsque l'on modifie une carac

### ISSUE THREAD

**Issue by rdugau** [GoOz/wfrp-sheet#11]
La **somme** des blessures ne se mets pas à jour lorsque l'on modifie une carac
![image](https://user-images.githubusercontent.com/56961532/218711084-81084bec-3a6f-45fa-a29c-5fe5198cc66b.png)

**Comment by GoOz** [comment]
J'ai cassé des choses 😭
