### ISSUE TITLE
Difficile de lire le texte des combos en mode dark

### ISSUE THREAD

**Issue by rdugau** [GoOz/wfrp-sheet#12]
Difficile de lire le texte des combos en mode dark

![image](https://user-images.githubusercontent.com/56961532/218712336-49a98d09-1668-40bb-a90f-b71ded07b510.png)

**Comment by GoOz** [comment]
Sur quel navigateur (+ version) et OS ? Parce que je reproduis pas sur MacOS FF/Chrome/Safari

**Comment by rdugau** [comment]
Chrome/Windows

**Comment by GoOz** [comment]
faut que je me trouve un environnement pour tester ça.

**Comment by GoOz** [comment]
<img width="286" alt="image" src="https://user-images.githubusercontent.com/1280069/218717104-cf7a1a60-27e8-4f61-9e08-cd470b2b711e.png">

MacOS > Windows :P

**Comment by rdugau** [comment]
Ah. Effectivement c'est mieux.
On dirais que la couleur des combos est mal gérées en darkmode

Par contre ta police n'est pas bonne ;-) Beaucoup plus beau sur W

**Comment by GoOz** [comment]
Fixed.
