### ISSUE TITLE
L'encombrement des armures semble ne pas se mettre à jour

### ISSUE THREAD

**Issue by rdugau** [GoOz/wfrp-sheet#13]
L'encombrement des armures semble ne pas se mettre à jour

![image](https://user-images.githubusercontent.com/56961532/218713078-23c1c240-9130-4b81-802a-a87778f2e8bb.png)

**Comment by GoOz** [comment]
Ah oui  en effet, c'est pas pris en compte quand la checkbox porté n'est pas cochée, j'ai dû cassé un truc.
